install:
    game-settings:
        accountId: 212090967
        modified: false
        timestamp: 1558288071047
    gameflow-patcher-lock: 1558289046807
    gameflow-process-info: null
    gameflow-spectate-reconnect-info: null
    globals:
        locale: "en_US"
        region: "NA"
    icon_version: 2
    last-valid-login-splash:
        theme: "battleAcademy"
        version: "1.55"
    lcu-settings:
        accountId: 212090967
        modified: false
        timestamp: 1558279051779
    licensesAgreedTo:
        576F00F89F0C6BED5C0B5166E2D6D1F7: null
    login-remember-me:
        rememberMe: true
        username: "kevin76000"
    npe-splash:
        enableNewPlayerSplash: false
    patcher:
        client_migrated: false
        client_patcher_available: false
        game_migrated: true
        game_patcher_available: true
        game_patcher_migrated_time: "2019-05-10T18:34:16Z"
        locales:
        - "en_US"
        toggles:
            concurrent_manifest: 2169378237
            new_client_patcher: 1170522097
            new_game_patcher: 462816454
    perks-settings:
        accountId: 212090967
        modified: false
        timestamp: 1558286170896
    rso-auth:
        install-identifier: "13be4183fceec847baa3eabc41f7ec53"
    telemetry:
        fresh_installation: false
        installation_id: "CzjjVw=="
