install:
    game-settings:
        accountId: 212090967
        modified: false
        timestamp: 1571374743104
    gameflow-patcher-lock: 1571378137277
    gameflow-process-info:
        pid: 17416
        rawArgs:
        - "192.64.173.230 5384 ybMnTPv4bDXdndpFTC6mGg== 49331082"
        - "-PlayerID=49331082"
        - "-GameID=3177497737"
    gameflow-spectate-reconnect-info: null
    globals:
        locale: "en_US"
        region: "NA"
    last-valid-login-splash:
        theme: "worlds2019"
        version: "1.60"
    lcu-settings:
        accountId: 212090967
        modified: false
        timestamp: 1571373208843
    licensesAgreedTo:
        576F00F89F0C6BED5C0B5166E2D6D1F7: null
    login-remember-me:
        rememberMe: false
        username: ""
    npe-splash:
        enableNewPlayerSplash: false
    patcher:
        client_migrated: true
        client_patcher_available: true
        client_patcher_migrated_time: "2019-09-28T05:55:09Z"
        game_migrated: true
        game_patcher_available: true
        game_patcher_migrated_time: "2019-09-28T05:55:09Z"
        locales:
        - "en_US"
        toggles:
            new_client_patcher: 4051976166
            new_game_patcher: 2333226970
    perks-settings:
        accountId: 212090967
        modified: false
        timestamp: 1571375138609
    riotclient-upgrade:
        aux-environment: "live"
        installer-decrypt-key: "ZuV40vGHTGYoUCpx"
        installer-filename: "rc-win.enc"
        seq-success-count: 74
        success-count: 74
        uninstaller-repaired: true
        upgrade-ready: true
    rso-auth:
        install-identifier: "ae3aca674e01ed44996da526796f8f92"
    telemetry:
        fresh_installation: false
        installation_id: "Q6f1ew=="
