install:
    game-settings:
        accountId: 212090967
        modified: false
        timestamp: 1555205634730
    gameflow-patcher-lock: null
    gameflow-process-info: null
    gameflow-spectate-reconnect-info: null
    globals:
        locale: "en_US"
        region: "NA"
    icon_version: 2
    last-valid-login-splash:
        theme: "seasonstart2019-c"
        version: "1.50"
    lcu-settings:
        accountId: 212090967
        modified: false
        timestamp: 1555204607937
    licensesAgreedTo:
        576F00F89F0C6BED5C0B5166E2D6D1F7: null
    login-remember-me:
        rememberMe: true
        username: "kevin76000"
    npe-splash:
        enableNewPlayerSplash: false
    patcher:
        client_migrated: false
        client_patcher_available: false
        game_migrated: true
        game_patcher_available: true
        locales:
        - "en_US"
        toggles:
            new_client_patcher: 1453211588
            new_game_patcher: 1840081899
    perks-settings:
        accountId: 212090967
        modified: false
        timestamp: 1555204608007
    rso-auth:
        install-identifier: "6405355aff98a44e9c9868278cd24781"
    telemetry:
        fresh_installation: false
        installation_id: "5f+LKQ=="
