install:
    crash_reporting:
        type: "crashpad"
    game-settings:
        accountId: 212090967
        modified: false
        timestamp: 1589575661255
    gameflow-patcher-lock: 1589577626997
    gameflow-process-info: null
    gameflow-spectate-reconnect-info: null
    globals:
        locale: "en_US"
        region: "NA"
    icon_version: 2
    last-valid-login-splash:
        theme: "worlds2019"
        version: "1.60"
    lcu-settings:
        accountId: 212090967
        modified: false
        timestamp: 1589569891347
    licensesAgreedTo:
        576F00F89F0C6BED5C0B5166E2D6D1F7: null
        F1110FCAE57FA8F7ABB49F7E88FB4EF6: null
        FD05EED4443B9F2164C2F9FC29CC2F47: null
    login-remember-me:
        rememberMe: true
        username: "cesica"
    npe-splash:
        enableNewPlayerSplash: false
    patcher:
        client_migrated: true
        client_patcher_available: true
        client_patcher_migrated_time: "2019-05-23T04:15:35Z"
        game_migrated: true
        game_patcher_available: true
        game_patcher_migrated_time: "2019-05-07T05:03:13Z"
        locales:
        - "en_US"
        migrated: false
        toggles:
            concurrent_manifest: 3825145451
            new_client_patcher: 0
            new_game_patcher: 0
    perks-settings:
        accountId: 212090967
        modified: false
        timestamp: 1589576726430
    riotclient-upgrade:
        seq-success-count: 260
        success-count: 260
        uninstaller-updated: true
    rso-auth:
        install-identifier: "bf0e85434fda4a2897bef6b2a1570d7f"
    splash:
        disableAnimation: true
    telemetry:
        fresh_installation: false
        installation_id: "hlk5EA=="
